/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";
import { Route as QuestionPapersIndexImport } from "./routes/question-papers/index";

// Create/Update Routes

const IndexRoute = IndexImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => rootRoute,
} as any);

const QuestionPapersIndexRoute = QuestionPapersIndexImport.update({
    id: "/question-papers/",
    path: "/question-papers/",
    getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
    interface FileRoutesByPath {
        "/": {
            id: "/";
            path: "/";
            fullPath: "/";
            preLoaderRoute: typeof IndexImport;
            parentRoute: typeof rootRoute;
        };
        "/question-papers/": {
            id: "/question-papers/";
            path: "/question-papers";
            fullPath: "/question-papers";
            preLoaderRoute: typeof QuestionPapersIndexImport;
            parentRoute: typeof rootRoute;
        };
    }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
    "/": typeof IndexRoute;
    "/question-papers": typeof QuestionPapersIndexRoute;
}

export interface FileRoutesByTo {
    "/": typeof IndexRoute;
    "/question-papers": typeof QuestionPapersIndexRoute;
}

export interface FileRoutesById {
    __root__: typeof rootRoute;
    "/": typeof IndexRoute;
    "/question-papers/": typeof QuestionPapersIndexRoute;
}

export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath;
    fullPaths: "/" | "/question-papers";
    fileRoutesByTo: FileRoutesByTo;
    to: "/" | "/question-papers";
    id: "__root__" | "/" | "/question-papers/";
    fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
    IndexRoute: typeof IndexRoute;
    QuestionPapersIndexRoute: typeof QuestionPapersIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
    IndexRoute: IndexRoute,
    QuestionPapersIndexRoute: QuestionPapersIndexRoute,
};

export const routeTree = rootRoute
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/question-papers/"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/question-papers/": {
      "filePath": "question-papers/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
